plugins {
    id 'dev.architectury.loom' version "${architectury_loom_version}" apply false
}

subprojects {
    apply plugin: 'java'

    group = project.maven_group
    version = project.mod_version

    base {
        archivesName = project.archives_base_name + '-' + project.name
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
        withSourcesJar()
    }

    jar {
        from rootProject.file('LICENSE')
    }

    repositories {
        mavenCentral()
        maven { url "https://maven.fabricmc.net/" }
        maven { url "https://maven.neoforged.net/releases" }
        maven { url "https://maven.parchmentmc.org" }
        maven { url "https://maven.architectury.dev/" }
        maven {
            url "https://jitpack.io"
            content { includeGroupByRegex "io\\.github\\.llamalad7\\..*" }
        }
    }
}
