plugins {
	id 'fabric-loom' version "1.17.17"
	id 'java'
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

base.archivesName = project.archives_base_name
version = project.mod_version
group = project.maven_group

repositories {
	mavenCentral()
	maven { url "https://maven.fabricmc.net/" }
	maven { url "https://maven.quiltmc.org/repository/release" }
	maven { url "https://maven.parchmentmc.org" }
	maven {
		url "https://jitpack.io"
		content { includeGroupByRegex "io\\.github\\.llamalad7\\..*" }
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

	compileOnly "io.github.llamalad7:mixinextras-common:0.2.2"
	annotationProcessor "io.github.llamalad7:mixinextras-common:0.2.2"
	compileOnly "io.github.llamalad7:mixinextras-fabric:0.2.2"
}

processResources {
	inputs.property "version", project.version
	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

java {
	withSourcesJar()
}

jar {
	from "LICENSE"
}

loom {
	mixin {
		useLegacyMixinAp = true
		defaultRefmapName = "impaled.refmap.json"
	}
	runs {
		client {
			environment = "client"
			configName = "Minecraft Client"
			runDir = "run/client"
		}
		server {
			environment = "server"
			configName = "Minecraft Server"
			runDir = "run/server"
		}
	}
}