pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'NeoForged'
            url = 'https://maven.neoforged.net/releases'
        }
        maven {
            name = 'Architectury'
            url = 'https://maven.architectury.dev/'
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

include ':fabric', ':neoforge'
rootProject.name = 'Impaled'
