plugins {
    id 'dev.architectury.loom'
}

sourceSets {
    main {
        java.srcDir rootProject.file('common/src/main/java')
        resources.srcDir rootProject.file('common/src/main/resources')
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.layered {
        it.mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
        it.mappings "dev.architectury:yarn-mappings-patch-neoforge:${project.yarn_patch_neoforge}"
    }
    neoForge "net.neoforged:neoforge:${project.neoforge_version}"

    compileOnly "io.github.llamalad7:mixinextras-common:0.2.2"
    annotationProcessor "io.github.llamalad7:mixinextras-common:0.2.2"
    compileOnly "net.fabricmc:sponge-mixin:0.15.5+mixin.0.8.7"
    annotationProcessor "net.fabricmc:sponge-mixin:0.15.5+mixin.0.8.7"
}

processResources {
    inputs.property "version", project.version
    filesMatching("META-INF/neoforge.mods.toml") {
        expand "version": project.version
    }
}

loom {
    mixin {
        useLegacyMixinAp = true
        defaultRefmapName = "impaled.refmap.json"
    }
    runs {
        client {
            environment = "client"
            configName = "Minecraft Client"
            runDir = "run/client"
        }
        server {
            environment = "server"
            configName = "Minecraft Server"
            runDir = "run/server"
        }
    }
}
